[package]
name = "text-to-png"
version = "0.1.0"
edition = "2018"
authors = ["Kevin Guthrie <kevin.guthrie@gmail.com>"]

[dependencies]
fontdb="0.7.0"
usvg="0.19.0"
resvg={version = "0.19.0", default-features = false, features = ["text"] }
tiny-skia="0.6.1"
eyre="0.6.5"